[2024-08-14T19:23:58.620+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.process_olist_customers.load_olist_customers_to_gcs manual__2024-08-14T19:20:39.229117+00:00 [queued]>
[2024-08-14T19:23:58.634+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.process_olist_customers.load_olist_customers_to_gcs manual__2024-08-14T19:20:39.229117+00:00 [queued]>
[2024-08-14T19:23:58.635+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2024-08-14T19:23:58.738+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresToGCSOperator): process_olist_customers.load_olist_customers_to_gcs> on 2024-08-14 19:20:39.229117+00:00
[2024-08-14T19:23:58.752+0000] {standard_task_runner.py:57} INFO - Started process 26467 to run task
[2024-08-14T19:23:58.759+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_bigquery_etl', 'process_olist_customers.load_olist_customers_to_gcs', 'manual__2024-08-14T19:20:39.229117+00:00', '--job-id', '529', '--raw', '--subdir', 'DAGS_FOLDER/extract_from_pg.py', '--cfg-path', '/tmp/tmprlsjbj9a']
[2024-08-14T19:23:58.763+0000] {standard_task_runner.py:85} INFO - Job 529: Subtask process_olist_customers.load_olist_customers_to_gcs
[2024-08-14T19:23:58.928+0000] {task_command.py:415} INFO - Running <TaskInstance: postgres_to_bigquery_etl.process_olist_customers.load_olist_customers_to_gcs manual__2024-08-14T19:20:39.229117+00:00 [running]> on host d81d956e7878
[2024-08-14T19:23:59.134+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-08-14T19:23:59.350+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_bigquery_etl' AIRFLOW_CTX_TASK_ID='process_olist_customers.load_olist_customers_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T19:20:39.229117+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T19:20:39.229117+00:00'
[2024-08-14T19:23:59.352+0000] {sql_to_gcs.py:161} INFO - Executing query
[2024-08-14T19:23:59.379+0000] {base.py:73} INFO - Using connection ID 'source_postgres_db' for task execution.
[2024-08-14T19:23:59.507+0000] {sql_to_gcs.py:180} INFO - Writing local data files
[2024-08-14T19:24:06.770+0000] {sql_to_gcs.py:186} INFO - Uploading chunk file #0 to GCS.
[2024-08-14T19:24:06.779+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-08-14T19:24:06.783+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-08-14T19:24:10.890+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x70bfc612f640>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /token
[2024-08-14T19:24:14.941+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x70bfc612f7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /token
[2024-08-14T19:25:01.569+0000] {gcs.py:564} INFO - File /tmp/tmprgzaj_j7 uploaded to data/olist_customers_20240814_192039.json in stg-olist-ecommerce-dataset2 bucket
[2024-08-14T19:25:01.569+0000] {sql_to_gcs.py:189} INFO - Removing local file
[2024-08-14T19:25:01.674+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=postgres_to_bigquery_etl, task_id=process_olist_customers.load_olist_customers_to_gcs, execution_date=20240814T192039, start_date=20240814T192358, end_date=20240814T192501
[2024-08-14T19:25:01.766+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-14T19:25:01.826+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
