[2024-08-17T19:10:06.507+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.create_bigquery_dataset manual__2024-08-17T19:09:55.908657+00:00 [queued]>
[2024-08-17T19:10:06.524+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.create_bigquery_dataset manual__2024-08-17T19:09:55.908657+00:00 [queued]>
[2024-08-17T19:10:06.524+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2024-08-17T19:10:06.579+0000] {taskinstance.py:1380} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_bigquery_dataset> on 2024-08-17 19:09:55.908657+00:00
[2024-08-17T19:10:06.589+0000] {standard_task_runner.py:57} INFO - Started process 585 to run task
[2024-08-17T19:10:06.594+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_bigquery_etl', 'create_bigquery_dataset', 'manual__2024-08-17T19:09:55.908657+00:00', '--job-id', '751', '--raw', '--subdir', 'DAGS_FOLDER/extract_from_pg.py', '--cfg-path', '/tmp/tmp_mzgjkli']
[2024-08-17T19:10:06.598+0000] {standard_task_runner.py:85} INFO - Job 751: Subtask create_bigquery_dataset
[2024-08-17T19:10:06.731+0000] {task_command.py:415} INFO - Running <TaskInstance: postgres_to_bigquery_etl.create_bigquery_dataset manual__2024-08-17T19:09:55.908657+00:00 [running]> on host c04129f4379c
[2024-08-17T19:10:07.387+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_bigquery_etl' AIRFLOW_CTX_TASK_ID='create_bigquery_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T19:09:55.908657+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-17T19:09:55.908657+00:00'
[2024-08-17T19:10:07.402+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-08-17T19:10:07.412+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-08-17T19:10:07.413+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value olist_ecommerce_dataset.
[2024-08-17T19:10:07.413+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value utility-range-425622-c7.
[2024-08-17T19:10:07.414+0000] {bigquery.py:481} INFO - Creating dataset: olist_ecommerce_dataset in project: utility-range-425622-c7 
[2024-08-17T19:10:10.616+0000] {bigquery.py:485} INFO - Dataset created successfully.
[2024-08-17T19:10:10.668+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=postgres_to_bigquery_etl, task_id=create_bigquery_dataset, execution_date=20240817T190955, start_date=20240817T191006, end_date=20240817T191010
[2024-08-17T19:10:10.709+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-17T19:10:10.781+0000] {taskinstance.py:2776} INFO - 9 downstream tasks scheduled from follow-on schedule check
